/*
-- Query: select * from customers
LIMIT 0, 1000

-- Date: 2026-05-09 21:55
*/
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('VINET','Vins et alcools Chevalier','Paul Henriot','Accounting Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('WARTH','Wartian Herkku','Pirkko Koskitalo','Accounting Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('ERNSH','Ernst Handel','Roland Mendel','Sales Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('RICSU','Richter Supermarkt','Michael Holz','Sales Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('FOLKO','Folk och fa HB','Maria Larsson','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('GROSR','GROSELLA-Restaurante','Manuel Pereira','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('RATTC','Rattlesnake Canyon Grocery','Paula Wilson','Assistant Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('TOMSP','Toms Spezialitaten','Karin Josephs','Marketing Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('BERGS','Berglunds snabbkop','Christina Berglund','Order Administrator');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('CHOPS','Chop-suey Chinese','Yang Wang','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('MAGAA','Magazzini Alimentari Riuniti','Giovanni Rovelli','Marketing Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('HANAR','Hanari Carnes','Mario Pontes','Accounting Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('FRANK','Frankenversand','Peter Franken','Marketing Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('OTTIK','Ottilies Kaseladen','Henriette Pfalzheim','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('LILAS','LILA-Supermercado','Carlos Gonzlez','Accounting Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('VICTE','Victuailles en stock','Mary Saveley','Sales Agent');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('BLONP','Blondesddsl pere et fils','Frederique Citeaux','Marketing Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('LEHMS','Lehmanns Marktstand','Renate Messner','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('HILAA','HILARION-Abastos','Carlos Hernndez','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('SUPRD','Supremes delices','Pascale Cartrain','Accounting Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('CENTC','Centro comercial Moctezuma','Francisco Chang','Marketing Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('QUEDE','Que Delicia','Bernardo Batista','Accounting Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('WHITC','White Clover Markets','Karl Jablonski','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('MORGK','Morgenstern Gesundkost','Alexander Feuer','Marketing Assistant');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('WELLI','Wellington Importadora','Paula Parente','Sales Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('SPLIR','Split Rail Beer & Ale','Art Braunschweiger','Sales Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('QUICK','QUICK-Stop','Horst Kloss','Accounting Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('ROMEY','Romero y tomillo','Alejandra Camino','Accounting Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('TORTU','Tortuga Restaurante','Miguel Angel Paolino','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('RICAR','Ricardo Adocicados','Janete Limeira','Assistant Sales Agent');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('REGGC','Reggiani Caseifici','Maurizio Moroni','Sales Associate');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('BSBEV','B\'s Beverages','Victoria Ashworth','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('COMMI','Comercio Mineiro','Pedro Afonso','Sales Associate');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('TRADH','Tradicao Hipermercados','Anabela Domingues','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('HUNGO','Hungry Owl All-Night Grocers','Patricia McKenna','Sales Associate');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('WANDK','Die Wandernde Kuh','Rita Muller','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('GODOS','Godos Cocina Tipica','Jose Pedro Freyre','Sales Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('OLDWO','Old World Delicatessen','Rene Phillips','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('LONEP','Lonesome Pine Restaurant','Fran Wilson','Sales Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('ANATR','Ana Trujillo Emparedados y helados','Ana Trujillo','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('THEBI','The Big Cheese','Liz Nixon','Marketing Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('DUMON','Du monde entier','Janine Labrune','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('ISLAT','Island Trading','Helen Bennett','Marketing Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('PERIC','Pericles Comidas clsicas','Guillermo Fernndez','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('KOENE','Koniglich Essen','Philip Cramer','Sales Associate');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('SAVEA','Save-a-lot Markets','Jose Pavarotti','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('BOLID','Bolido Comidas preparadas','Martin Sommer','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('FURIB','Furia Bacalhau e Frutos do Mar','Lino Rodriguez','Sales Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('BONAP','Bon app\'','Laurence Lebihan','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('MEREP','Mere Paillarde','Jean Fresniere','Marketing Assistant');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('PRINI','Princesa Isabel Vinhos','Isabel de Castro','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('SIMOB','Simons bistro','Jytte Petersen','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('FAMIA','Familia Arquibaldo','Aria Cruz','Marketing Assistant');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('LAMAI','La maison d\'Asie','Annette Roulet','Sales Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('PICCO','Piccolo und mehr','Georg Pipps','Sales Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('AROUT','Around the Horn','Thomas Hardy','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('SEVES','Seven Seas Imports','Hari Kumar','Sales Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('DRACD','Drachenblut Delikatessen','Sven Ottlieb','Order Administrator');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('EASTC','Eastern Connection','Ann Devon','Sales Agent');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('ANTON','Antonio Moreno Taqueria','Antonio Moreno','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('GALED','Galeria del gastronomo','Eduardo Saavedra','Marketing Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('VAFFE','Vaffeljernet','Palle Ibsen','Sales Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('QUEEN','Queen Cozinha','Lucia Carvalho','Marketing Assistant');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('WOLZA','Wolski  Zajazd','Zbyszek Piestrzeniewicz','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('HUNGC','Hungry Coyote Import Store','Yoshi Latimer','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('SANTG','Sante Gourmet','Jonas Bergulfsen','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('BOTTM','Bottom-Dollar Markets','Elizabeth Lincoln','Accounting Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('LINOD','LINO-Delicateses','Felipe Izquierdo','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('FOLIG','Folies gourmandes','Martine Rance','Assistant Sales Agent');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('OCEAN','Oceano Atlntico Ltda.','Yvonne Moncada','Sales Agent');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('FRANS','Franchi S.p.A.','Paolo Accorti','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('GOURL','Gourmet Lanchonetes','Andre Fonseca','Sales Associate');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('CONSH','Consolidated Holdings','Elizabeth Brown','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('RANCH','Rancho grande','Sergio Gutierrez','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('LAZYK','Lazy K Kountry Store','John Steel','Marketing Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('LAUGB','Laughing Bacchus Wine Cellars','Yoshi Tannamuri','Marketing Assistant');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('BLAUS','Blauer See Delikatessen','Hanna Moos','Sales Representative');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('NORTS','North/South','Simon Crowther','Sales Associate');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('CACTU','Cactus Comidas para llevar','Patricio Simpson','Sales Agent');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('GREAL','Great Lakes Food Market','Howard Snyder','Marketing Manager');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('MAISD','Maison Dewey','Catherine Dewey','Sales Agent');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('TRAIH','Trail\'s Head Gourmet Provisioners','Helvetius Nagy','Sales Associate');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('LETSS','Let\'s Stop N Shop','Jaime Yorres','Owner');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('WILMK','Wilman Kala','Matti Karttunen','Owner/Marketing Assistant');
INSERT INTO `` (`customerID`,`companyName`,`contactName`,`contactTitle`) VALUES ('THECR','The Cracker Box','Liu Wong','Marketing Assistant');
